"""macOS Seatbelt (sandbox-exec) profile plan generation.

Generates a conservative .sb profile text from a SandboxExecutionRequest.
This is profile preview only — sandbox-exec is never invoked.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path

from safecode.config import SafeCodeConfig
from safecode.sandbox.adapter import SandboxExecutionRequest
from safecode.sandbox.filesystem import FilesystemBoundary

SYSTEM_READ_PATHS = [
    "/usr",
    "/bin",
    "/System/Library",
    "/Library",
    "/dev/null",
    "/dev/random",
    "/dev/urandom",
    "/dev/stdin",
    "/dev/stdout",
    "/dev/stderr",
]

SENSITIVE_SEGMENTS = {
    ".env",
    ".ssh",
    ".aws",
    "id_rsa",
    "id_dsa",
    "credentials",
    "token",
    "secret",
    "password",
    ".pem",
    ".key",
    ".p12",
}


@dataclass(frozen=True)
class SeatbeltProfilePlan:
    """Generated macOS sandbox profile plan."""

    profile_text: str
    readonly_filesystem: bool
    network_enabled: bool
    allowed_read_paths: list[str] = field(default_factory=list)
    allowed_write_paths: list[str] = field(default_factory=list)
    denied_paths: list[str] = field(default_factory=list)
    warnings: list[str] = field(default_factory=list)


class SeatbeltProfileBuilder:
    """Build a conservative macOS Seatbelt profile from a request."""

    def __init__(self, project_root: Path, config: SafeCodeConfig) -> None:
        self.project_root = project_root.resolve()
        self.config = config
        self.filesystem = FilesystemBoundary(project_root, config)
        self._sensitive = set(config.sandbox.sensitive_names) | SENSITIVE_SEGMENTS

    def build(self, request: SandboxExecutionRequest) -> SeatbeltProfilePlan:
        """Generate Seatbelt profile plan. Never executes sandbox-exec."""
        warnings: list[str] = [
            "This is a development preview profile — not production-ready.",
            "Profile is generated for review only. sandbox-exec was NOT invoked.",
            "System paths are whitelisted broadly; tighten for production use.",
        ]
        allowed_read: list[str] = []
        allowed_write: list[str] = []
        denied: list[str] = []

        project_str = str(self.project_root)
        allowed_read.append(project_str)

        for sys_path in SYSTEM_READ_PATHS:
            allowed_read.append(sys_path)

        for path in request.writable_paths:
            try:
                resolved = self.filesystem.validate(path)
                resolved_str = str(resolved)
                if not request.readonly_filesystem:
                    if self._is_sensitive_path(resolved):
                        warnings.append(
                            f"Writable path {path} includes a sensitive path segment; "
                            "profile will not grant write access to it."
                        )
                        continue
                    if not self._path_starts_with(resolved, self.project_root):
                        warnings.append(
                            f"Writable path {path} is outside project root; "
                            "profile will not grant write access to it."
                        )
                        continue
                    allowed_write.append(resolved_str)
                allowed_read.append(resolved_str)
            except PermissionError:
                warnings.append(f"Writable path rejected by FilesystemBoundary: {path}")

        for sensitive in sorted(self._sensitive):
            denied_path = f"{project_str}/**/{sensitive}*"
            denied.append(denied_path)
            if not request.readonly_filesystem:
                denied.append(f"{project_str}/{sensitive}*")

        profile_lines = self._build_profile_text(request, allowed_read, allowed_write, denied, warnings)
        profile_text = "\n".join(profile_lines) + "\n"

        return SeatbeltProfilePlan(
            profile_text=profile_text,
            readonly_filesystem=request.readonly_filesystem,
            network_enabled=request.allow_network,
            allowed_read_paths=allowed_read,
            allowed_write_paths=allowed_write,
            denied_paths=denied,
            warnings=warnings,
        )

    def _build_profile_text(
        self,
        request: SandboxExecutionRequest,
        allowed_read: list[str],
        allowed_write: list[str],
        denied: list[str],
        warnings: list[str],
    ) -> list[str]:
        lines: list[str] = []

        lines.append("(version 1)")
        lines.append("")
        lines.append(f";; Auto-generated by SafeCode Agent v1.7.1")
        lines.append(f";; Purpose: {request.purpose}")
        lines.append(f";; Generated for preview only — sandbox-exec was NOT executed")
        lines.append("")

        lines.append("(deny default)")
        lines.append("")

        lines.append(";; ── basic process operations ──")
        lines.append('(allow process-exec)')
        lines.append('(allow process-fork)')
        lines.append('(allow signal)')
        lines.append('(allow sysctl-read)')
        lines.append("")

        lines.append(";; ── allowed file read paths ──")
        for path in sorted(set(allowed_read)):
            escaped = self._escape_sb_path(path)
            lines.append(f'(allow file-read* (subpath "{escaped}"))')
        lines.append("")

        if allowed_write:
            lines.append(";; ── allowed file write paths ──")
            for path in sorted(set(allowed_write)):
                escaped = self._escape_sb_path(path)
                lines.append(f'(allow file-write* (subpath "{escaped}"))')
            lines.append("")

        if denied:
            lines.append(";; ── explicitly denied paths ──")
            for path in sorted(set(denied)):
                escaped = self._escape_sb_path(path)
                lines.append(f'(deny file-read* (subpath "{escaped}"))')
                lines.append(f'(deny file-write* (subpath "{escaped}"))')
            lines.append("")

        lines.append(";; ── network ──")
        if request.allow_network:
            lines.append("(allow network-outbound)")
            lines.append("(allow network-inbound)")
            lines.append("(allow system-socket)")
            warnings.append(
                "Network access is allowed in profile but not validated. "
                "v1.7.1 generates profile only — no execution."
            )
        else:
            lines.append(";; network access is DISABLED by policy")
            lines.append("")

        return lines

    @staticmethod
    def _escape_sb_path(path: str) -> str:
        return path.replace("\\", "\\\\").replace('"', '\\"')

    def _is_sensitive_path(self, path: Path) -> bool:
        lowered_parts = {part.lower() for part in path.parts}
        lowered_name = path.name.lower()
        for sensitive in self._sensitive:
            lowered_sensitive = sensitive.lower()
            if lowered_sensitive in lowered_parts:
                return True
            if lowered_sensitive in lowered_name:
                return True
        return False

    @staticmethod
    def _path_starts_with(path: Path, parent: Path) -> bool:
        try:
            path.relative_to(parent)
            return True
        except ValueError:
            return False
