# Homebrew formula for safecode-agent (auto-generated by scripts/update-brew-formula.sh)
# Do not edit manually — regenerate with: scripts/update-brew-formula.sh <version> <sha256>
#
# Install from the homebrew-safecode tap:
#   brew install safecode/tap/safecode-agent

class SafecodeAgent < Formula
  include Language::Python::Virtualenv

  desc "Safety-first terminal coding agent with diff review, checkpoints, rollback, and audit logs"
  homepage "https://github.com/safecode/safecode-agent"
  url "https://files.pythonhosted.org/packages/source/s/safecode-agent/safecode_agent-5.5.0.tar.gz"
  sha256 "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb"
  license "MIT"

  depends_on "python@3.11"
  depends_on "pipx"

  def install
    # Use pipx to install into an isolated environment; expose the sac binary.
    system "pipx", "install", "safecode-agent==5.5.0",
           "--python", Formula["python@3.11"].opt_bin/"python3.11"
    # Link the sac binary so 'brew link' can expose it.
    bin.install_symlink Dir["#{HOMEBREW_PREFIX}/bin/sac"]
  end

  test do
    system "#{bin}/sac", "version"
  end
end
