"""Schemas for structured agent responses."""

from pydantic import BaseModel


class AgentAnswer(BaseModel):
    """Read-only natural language answer."""

    type: str = "answer"
    content: str


class AgentPatchResponse(BaseModel):
    """Patch response generated by an LLM client."""

    type: str = "patch"
    patch_text: str
    explanation: str | None = None


class AgentError(BaseModel):
    """Structured error response from an LLM client."""

    type: str = "error"
    message: str
