"""Schemas for structured agent responses."""

from __future__ import annotations

import json
import re
from dataclasses import dataclass
from typing import Annotated, Literal

from pydantic import BaseModel, Field, TypeAdapter, ValidationError

from safecode.agent.tools import ToolIntent


class AgentAnswer(BaseModel):
    """Read-only natural language answer."""

    type: Literal["answer"] = "answer"
    content: str


class AgentPlanResponse(BaseModel):
    """Structured plan response for a user goal."""

    type: Literal["plan"] = "plan"
    goal: str
    steps: list[str] = Field(min_length=1)


class AgentToolIntentResponse(BaseModel):
    """Structured request to route a tool intent."""

    type: Literal["tool_intent"] = "tool_intent"
    intent: ToolIntent
    rationale: str | None = None


class AgentPatchResponse(BaseModel):
    """Patch response generated by an LLM client."""

    type: Literal["patch"] = "patch"
    patch_text: str
    explanation: str | None = None


class AgentStopForUserResponse(BaseModel):
    """Structured stop when the agent needs user input or approval."""

    type: Literal["stop_for_user"] = "stop_for_user"
    reason: str
    message: str
    requires_approval: bool = True


class AgentError(BaseModel):
    """Structured error response from an LLM client."""

    type: Literal["error"] = "error"
    message: str


@dataclass(frozen=True)
class RecoverableContractFailure:
    """A transient, contract-shaped LLM failure that the agent loop may retry once.

    Distinct from ``LLMContractViolation`` (which is always fail-closed):
    the loop journals a ``loop_retry`` event and calls ``choose_tool()`` again
    exactly once. A second ``RecoverableContractFailure`` after the retry is
    treated as a permanent failure.

    Only explicitly scripted or detected recoverable failure conditions should
    produce this value — never user-stop, policy-block, or validation failure paths.
    """

    step: int
    method: str
    message: str


AgentContractResponse = Annotated[
    AgentAnswer
    | AgentPlanResponse
    | AgentToolIntentResponse
    | AgentPatchResponse
    | AgentStopForUserResponse
    | AgentError,
    Field(discriminator="type"),
]

_AGENT_CONTRACT_ADAPTER = TypeAdapter(AgentContractResponse)


def parse_agent_contract_response(raw: str | dict) -> AgentContractResponse:
    """Parse and validate one structured agent response."""
    data = _coerce_agent_json(raw)
    try:
        return _AGENT_CONTRACT_ADAPTER.validate_python(data)
    except ValidationError as exc:
        raise ValueError(f"Invalid agent contract response: {exc}") from exc


def _coerce_agent_json(raw: str | dict) -> dict:
    if isinstance(raw, dict):
        return raw

    text = raw.strip()
    fenced = re.fullmatch(r"```(?:json)?\s*(.*?)\s*```", text, re.DOTALL)
    if fenced:
        text = fenced.group(1).strip()

    try:
        data = json.loads(text)
    except json.JSONDecodeError as exc:
        raise ValueError(f"Agent response must be valid JSON: {exc}") from exc
    if not isinstance(data, dict):
        raise ValueError("Agent response JSON must be an object.")
    return data
