#!/usr/bin/env bash
# update-brew-formula.sh — generate or update the Homebrew formula for safecode-agent.
#
# Usage:
#   scripts/update-brew-formula.sh <version> <sha256_of_wheel>
#
# Output:
#   Formula/safecode-agent.rb  (created/overwritten)
#
# The formula uses a pipx shim to install the PyPI wheel so that the formula
# never embeds Python version assumptions.  Tested with Homebrew 4.x on macOS.
#
# Called automatically by 'sac release publish --update-brew' after a successful
# PyPI upload.

set -euo pipefail

VERSION="${1:-}"
SHA256="${2:-}"

if [[ -z "$VERSION" || -z "$SHA256" ]]; then
    echo "Usage: $0 <version> <sha256_of_wheel>" >&2
    exit 1
fi

FORMULA_DIR="$(git rev-parse --show-toplevel)/Formula"
mkdir -p "$FORMULA_DIR"

FORMULA_PATH="$FORMULA_DIR/safecode-agent.rb"

cat > "$FORMULA_PATH" << FORMULA
# Homebrew formula for safecode-agent (auto-generated by scripts/update-brew-formula.sh)
# Do not edit manually — regenerate with: scripts/update-brew-formula.sh <version> <sha256>
#
# Install from the homebrew-safecode tap:
#   brew install safecode/tap/safecode-agent

class SafecodeAgent < Formula
  include Language::Python::Virtualenv

  desc "Safety-first terminal coding agent with diff review, checkpoints, rollback, and audit logs"
  homepage "https://github.com/safecode/safecode-agent"
  url "https://files.pythonhosted.org/packages/source/s/safecode-agent/safecode_agent-${VERSION}.tar.gz"
  sha256 "${SHA256}"
  license "MIT"

  depends_on "python@3.11"
  depends_on "pipx"

  def install
    # Use pipx to install into an isolated environment; expose the sac binary.
    system "pipx", "install", "safecode-agent==${VERSION}",
           "--python", Formula["python@3.11"].opt_bin/"python3.11"
    # Link the sac binary so 'brew link' can expose it.
    bin.install_symlink Dir["#{HOMEBREW_PREFIX}/bin/sac"]
  end

  test do
    system "#{bin}/sac", "version"
  end
end
FORMULA

echo "Formula written to: $FORMULA_PATH"
echo "  version: $VERSION"
echo "  sha256:  $SHA256"
